#!/usr/bin/env bash

BASE_DIR="$(dirname ${BASH_SOURCE[0]})"

if [ ! -d $BASE_DIR/venv ]; then 
  python3 -m venv $BASE_DIR/venv
fi;

source $BASE_DIR/venv/bin/activate

# pip install -r $BASE_DIR/requirements.txt

if [ "${1}" == "shell" ]; then 
  python3
else
  $BASE_DIR/run.py $@
fi


deactivate
