apiVersion: v1
kind: Pod
metadata:
  name: {{ app_name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ manifest_name }}
    app.kubernetes.io/instance: {{ app_name }}
    app.kubernetes.io/part-of: {{ manifest_name }}
    app.kubernetes.io/version: "{{ image_tag }}"
    app.kubernetes.io/managed-by: asim
    app.kubernetes.io/component: database
spec:
  containers:
  - image: {{ image_name }}:{{ image_tag }}
    name: {{ app_name }}
    ports:
      - name: pod-main-port
        containerPort: 3306
    env:
      - name: BITNAMI_DEBUG
        value: "false"
      - name: MARIADB_ROOT_PASSWORD
        value: password
      - name: MARIADB_USER
        value: "user"
      - name: MARIADB_PASSWORD
        value: password
      - name: MARIADB_DATABASE
        value: "main_wordpress"

    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 120
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      exec:
        command:
          - /bin/bash
          - -ec
          - mysqladmin status -uroot -p"${MARIADB_ROOT_PASSWORD}"

    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      exec:
        command:
          - /bin/bash
          - -ec
          - mysqladmin status -uroot -p"${MARIADB_ROOT_PASSWORD}"

    volumeMounts:
      - name: mariadb-config
        mountPath: /opt/bitnami/mariadb/conf/my.cnf
        subPath: my.cnf

  volumes:
    - name: mariadb-config
      configMap:
        name: config-{{ app_name }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ app_name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ manifest_name }}
    app.kubernetes.io/instance: {{ app_name }}
    app.kubernetes.io/part-of: {{ manifest_name }}
    app.kubernetes.io/version: "{{ image_tag }}"
    app.kubernetes.io/managed-by: asim
    app.kubernetes.io/component: database
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    plugin_dir=/opt/bitnami/mariadb/plugin
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mariadb/plugin
    
    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

---

{% include 'apps/network/service.yaml' %}
