apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ namespace }}
  name: {{ app_name }}
  labels:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
    app.kubernetes.io/part-of: {{ manifest_name }}
    app.kubernetes.io/version: "{{ image_tag }}"
    app.kubernetes.io/managed-by: asim
    app.kubernetes.io/component: network
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ namespace }}.asim.com
    http:
      paths:
      - path: /{{ app_name }}
        pathType: Prefix
        backend:
          serviceName: {{ app_name }}
          servicePort: main
  tls:
  - hosts:
      - {{ namespace }}.asim.com
    secretName: certificate-{{ app_name }}
