apiVersion: v1
kind: Pod
metadata:
  name: app-name
  namespace: default
  labels:
    my: test-ingress
    type: main
spec:
  containers:
  - image: containous/whoami
    name: app-name

---

apiVersion: v1
kind: Service
metadata:
  name: app-name
  namespace: default
  labels:
    my: test-ingress
spec:
  type: ClusterIP
  selector:
    my: test-ingress
    type: main
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    