apiVersion: v1
kind: Pod
metadata:
  name: mariadb-{{ app_name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: asim
    app.kubernetes.io/component: database
spec:
  containers:
  - image: mariadb
    name: mariadb-{{ app_name }}
    envFrom:
    - secretRef:
        name: mysecret-{{ app_name }}
---

apiVersion: v1
kind: Secret
metadata:
  name: mysecret-{{ app_name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: asim
    app.kubernetes.io/component: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MWYyZDFlMmU2N2Rm

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb-{{ app_name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: asim
    app.kubernetes.io/component: network
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/managed-by: asim
    app.kubernetes.io/component: database
  ports:
  - name: main
    port: 3306
    protocol: TCP
    targetPort: 3306
