apiVersion: v1
kind: Pod
metadata:
  name: whoami-{{ app_name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
    app.kubernetes.io/part-of: whoami
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: asim
    app.kubernetes.io/component: server
spec:
  containers:
  - image: containous/whoami
    name: whoami-{{ app_name }}

---

apiVersion: v1
kind: Service
metadata:
  name: whoami-{{ app_name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
    app.kubernetes.io/part-of: whoami
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: asim
    app.kubernetes.io/component: network
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
    app.kubernetes.io/part-of: whoami
    app.kubernetes.io/managed-by: asim
    app.kubernetes.io/component: server
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ namespace }}
  name: whoami-{{ app_name }}
  labels:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
    app.kubernetes.io/part-of: whoami
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: asim
    app.kubernetes.io/component: network
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ app_name }}.asim.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: whoami-{{ app_name }}
          servicePort: 80
  tls:
  - hosts:
      - {{ app_name }}.asim.com
    secretName: certificate-{{ app_name }}
