apiVersion: v1
kind: Pod
metadata:
  name: {{ app_name }}
  namespace: {{ namespace }}
  labels:
    my: test-ingress
    type: main
spec:
  containers:
  - image: containous/whoami
    name: {{ app_name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ app_name }}
  namespace: {{ namespace }}
  labels:
    my: test-ingress
spec:
  type: ClusterIP
  selector:
    my: test-ingress
    type: main
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ namespace }}
  name: whoami-{{ app_name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ app_name }}.asim.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{ app_name }}
          servicePort: 80
  tls:
  - hosts:
      - {{ app_name }}.asim.com
    secretName: certificate-{{ app_name }}
