#!/usr/bin/env bash

set -eu

# Fail on a single failed command in a pipeline
set -o pipefail 


BASE_DIR="$(dirname $(dirname ${BASH_SOURCE[0]}))"

COMMAND=${1}
app_name=${2}
user_namespace=${3}
chart_name=${4:-}


# helm repo update


helm_install() {
  helm install ${app_name} bitnami/${chart_name} -n ${user_namespace} \
    --values ${BASE_DIR}/k8s/helm_values/bitnami/${chart_name}.yaml \
    --set ingress.hostname=${app_name}.asim.com
}


helm_update() {
  helm upgrade ${app_name} bitnami/${chart_name} -n ${user_namespace} \
    --values ${BASE_DIR}/k8s/helm_values/bitnami/${chart_name}.yaml \
    --set ingress.hostname=${app_name}.asim.com
}


case ${COMMAND} in

  "install")
    helm_install
    ;;

  "update" | "upgrade")
    helm_update
    ;;

  "delete")
    helm uninstall ${app_name} -n ${user_namespace}
    ;;

  *)
    exit 4
    ;;
esac
