#!/usr/bin/env bash

BASE_DIR="$(dirname $(dirname ${BASH_SOURCE[0]}))"

if [ ! -d $BASE_DIR/venv ]; then 
  python3 -m venv $BASE_DIR/venv
fi;

source $BASE_DIR/venv/bin/activate

$BASE_DIR/manage.py $@

deactivate
