wordpressEmail: user@example.com
wordpressFirstName: FirstName
wordpressLastName: LastName
wordpressBlogName: User's Blog!

wordpressUsername: user
wordpressPassword: "user"


# NOTE: ReadWriteMany PVC(s) are required if replicaCount > 1
replicaCount: 1


persistence:
  size: 1Gi


service:
  type: ClusterIP
  port: 80
  httpsPort: 443


ingress:
  enabled: true
  certManager: true
  tls: true


# ==============
# DATABASE
# ==============
mariadb:
  enabled: false

externalDatabase:
  host: data2-mariadb.default.svc
  port: 3306
  database: main_wordpress
  user: user
  
  password: "password"
  # OR
  # existingSecret: "app-name-mariadb"
  # Must contain key `mariadb-password`


# ==============
# SMTP 
# ==============
smtpHost: ""
smtpPort: ""
smtpUser: ""
smtpProtocol: ""

smtpPassword: ""
# OR
smtpExistingSecret:
# Must contain key `smtp-password`



# ==============
# OTHER 
# ==============
allowEmptyPassword: false
wordpressAutoUpdateLevel: major
wordpressPlugins: none

# Skip wizard installation
# NOTE: useful if you use an external database that already contains WordPress data
wordpressSkipInstall: false
# ref: https://github.com/bitnami/bitnami-docker-wordpress#connect-wordpress-docker-container-to-an-existing-database


# Custom post-init.d user scripts
# ref: https://github.com/bitnami/bitnami-docker-wordpress/tree/master/5/debian-10/rootfs/post-init.d
# NOTE: supported formats are `.sh`, `.sql` or `.php`
# NOTE: scripts are exclusively executed during the 1st boot of the container
# e.g:
# customPostInitScripts:
#   enable-multisite.sh: |
#     #!/bin/bash
#     chmod +w /bitnami/wordpress/wp-config.php
#     wp core multisite-install --url=example.com --title="Welcome to the WordPress Multisite" --admin_user="doesntmatternotreallyused" --admin_password="doesntmatternotreallyused" --admin_email="user@example.com"
#     cat /docker-entrypoint-init.d/.htaccess > /bitnami/wordpress/.htaccess
#     chmod -w bitnami/wordpress/wp-config.php
#   .htaccess: |
#     RewriteEngine On
#     RewriteBase /
#     ...
#
customPostInitScripts: {}


# WARN  ==> Multisite mode is not enabled, and WORDPRESS_MULTISITE_HOST is only used for Multisite installations. Its value will be ignored.
