name: PyPI Test

on:
  push:
    branches:
      - main

jobs:
  install_minikube_then_test:
    name: PyPI Test
    runs-on: ubuntu-latest

    strategy:
      # fail-fast: false
      matrix:
        minikube_version: ['v1.20.0', 'v1.21.0']
        kubernetes_version: ['v1.19.0', 'v1.20.0', 'v1.21.0']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.4.2
      with:
        minikube version: '${{ matrix.minikube_version }}'
        kubernetes version: '${{ matrix.kubernetes_version }}'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Wait for default service account
      run: |
        for i in {1..50}; do 
          sleep 1; 
          if kubectl get sa &> /dev/null; then break; fi; 
        done;

    - name: fix config file is world-readable
      run: chmod 600 ~/.kube/config

    - name: Run tests
      run: make py-test
