name: Test with Minikube

on:
  push:
    branches:
      - main

jobs:
  install_minikube_then_test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      # fail-fast: false
      matrix:
        minikube_version: ['v1.18.0', 'v1.19.0', 'v1.20.0', 'v1.21.0']
        kubernetes_version: ['v1.19.0', 'v1.20.0', 'v1.21.0']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.4.2
      with:
        minikube version: '${{ matrix.minikube_version }}'
        kubernetes version: '${{ matrix.kubernetes_version }}'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install requirements
      run: make install
    
    - name: Wait for default service account
      run: |
        for i in {1..50}; do 
          sleep 1; 
          if kubectl get sa &> /dev/null; then break; fi; 
        done;
        
    - name: Enable minikube ingress
      run: minikube addons enable ingress

    - name: fix config file is world-readable
      run: chmod 600 ~/.kube/config

    - run: sleep 30;

    - name: Set up network hosts
      run: |
        cat <<EOF | sudo tee -a /etc/hosts
        $(minikube ip)  django.tw0900.com
        $(minikube ip)  whoami.tw0900.com
        $(minikube ip)  mariadb.tw0900.com
        $(minikube ip)  phpmyadmin.tw0900.com
        $(minikube ip)  wordpress.tw0900.com
        $(minikube ip)  osclass.tw0900.com
        EOF

    - name: Run tests
      run: make test